language: python

python:
 - 3.6

branches:
  only:
    - dev

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - nvm install lts/dubnium
  - nvm use lts/dubnium
  - yarn

cache:
  pip: true
  yarn: true

script:
  - yarn test
  - yarn build
